# Runs on push to main, basically the "release" version since we don't really do releases (that's bad right)
name: Cargo Build

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**.json'
      - '**.yml'
      - 'LICENSE'
      - '!.github/workflows/cargo-build.yml'
      - 'installer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        # with:
        #   toolchain: nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test